### PR TITLE
Es 7.1

### PR DESCRIPTION
**Pull request by sam3oh5**
I refered Zakkery's work for es-6.0 and change his codes to be able to work on es-7.1.

Because scores produced by the script_score function must be non-negative on elasticsearch 7, I changed the returned score of dot product and cosine similarity. You can it in README.

### CODE REVIEW

**Comment by lior-k** [comment]
Right, Negative scores are not allowed in Lucene 8.
Thanks for the contribution sam3oh5 👌
Can you add a test for Elasticsearch 7.x?

**Comment by sam3oh5** [comment]
Okay. I added score tests for both of cosine similarity and dot-product into the plugintest scipt.

**Comment by lior-k** [comment]
Hi sam, you forgot to delete src/main/java/com/liorkn/elasticsearch/service/VectorScoringScriptEngineService.java

Apart from that it looks good.
Did you try to add the result zip file (from mvn install) to a live ES7?

**Comment by sam3oh5** [comment]
Thank you for comment, lior-k. I deleted that file. And surely I did test the result zip file to a live ES7 and it worked well.

**Comment by lior-k** [comment]
Good to hear. thanks sam.
hmm, I see that this MR is targeted to `master` on my repo.
I think it's best if it will be on a side branch named `es-7.1`.

**Comment by sam3oh5** [comment]
Yes, I hope so. However, github doesn't support for pull request to a new branch. Could you make es-7.1 branch? Or do you have any other solution?

**Comment by lior-k** [comment]
OK, I created branch es-7.1. please target your MR there.
Thanks!

**Comment by sam3oh5** [comment]
Thank you for creating new branch. I changed the base branch to es-7.1.

**Comment by snakeztc** [comment]
will it work on es-7.3?

**Pull request merged**
